version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7.2

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-
      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dist,lint,test,typehinting]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - venv

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8 pluscal

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: test
          command: |
            . venv/bin/activate
            nosetests pluscal

  typehinting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: typehinting
          command: |
            . venv/bin/activate
            mypy pluscal


workflows:
  version: 2
  build_and_release:
    jobs:
      - init:
          filters:
            # run for all branches and tags
            tags:
              only: /.*/
      - lint:
          requires:
            - init
          filters:
            # run for all branches and tags
            tags:
              only: /.*/
      - test:
          requires:
            - init
          filters:
            # run for all branches and tags
            tags:
              only: /.*/
      - typehinting:
          requires:
            - init
          filters:
            # run for all branches and tags
            tags:
              only: /.*/
